### ISSUE TITLE
Can't connect to device

### ISSUE THREAD

**Issue by rebel7580** [klausahrenberg/WThermostatBeca#53]
I have Gosund WP3 devices I'm trying to convert to Tasmota.
Running tuya-convert on a RPI zero with Wifi Dongle, and serial console. I  got my phone to connect to vtrust-flash at 10.42.42.26. Blue light on device is blinking. Here what I get when trying start_flash:

```
hvxl@rpia:~/tuya-convert$ ./start_flash.sh
Checking for network interface wlan0... Found.
Checking UDP port 53... ss: invalid option -- 'H'
Available.
Checking UDP port 67... ss: invalid option -- 'H'
Available.
Checking TCP port 80... ss: invalid option -- 'H'
Available.
Checking TCP port 443... ss: invalid option -- 'H'
Available.
Checking UDP port 6666... ss: invalid option -- 'H'
Available.
Checking UDP port 6667... ss: invalid option -- 'H'
Available.
Checking TCP port 1883... ss: invalid option -- 'H'
Available.
Checking TCP port 8886... ss: invalid option -- 'H'
Available.
======================================================
  Starting AP in a screen
  Starting web server in a screen
  Starting Mosquitto in a screen
  Starting PSK frontend in a screen
  Starting Tuya Discovery in a screen

======================================================

IMPORTANT
1. Connect any other device (a smartphone or something) to the WIFI vtrust-flash
   This step is IMPORTANT otherwise the smartconfig may not work!
2. Put your IoT device in autoconfig/smartconfig/pairing mode (LED will blink fast). This is usually done by pressing and holding the primary button of the device
   Make sure nothing else is plugged into your IoT device while attempting to flash.
3. Press ENTER to continue


======================================================
Starting smart config pairing procedure
Waiting for the device to install the intermediate firmware
Put device in EZ config mode (blinking fast)
Sending SSID                  vtrust-flash
Sending wifiPassword
Sending token                 00000000
Sending secret                0101
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
.................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
..................
SmartConfig complete.
Resending SmartConfig Packets
...
Device did not appear with the intermediate firmware
Check the *.log files in the scripts folder
Do you want to try flashing another device? [y/N]
```
Here's screenlog.0:

```
Traceback (most recent call last):
  File "./fake-registration-server.py", line 9, in <module>
    import tornado.web
  File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1655
    async def _execute(
            ^
SyntaxError: invalid syntax
Configuring AP interface...
RTNETLINK answers: File exists
RTNETLINK answers: File exists
Starting DNSMASQ server...
Starting AP on wlan0...
Configuration file: /dev/stdin
Using interface wlan0 with hwaddr 40:a5:ef:0e:d5:49 and ssid "vtrust-flash"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED
wlan0: AP-STA-CONNECTED d8:f1:5b:aa:bb:bb
1575998420: mosquitto version 1.4.14 (build date Mon, 10 Jul 2017 23:48:43 +0100) starting
1575998420: Using default config.
1575998420: Opening ipv4 listen socket on port 1883.
1575998420: Opening ipv6 listen socket on port 1883.
new client on port 443 from 10.42.42.40:7710
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:26780
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:40469
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
Listening for Tuya broadcast on UDP 6666
Listening for encrypted Tuya broadcast on UDP 6667
wlan0: AP-STA-CONNECTED a4:08:ea:27:80:37
new client on port 443 from 10.42.42.40:13054
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.26:50698
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:61202
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:20179
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
wlan0: AP-STA-DISCONNECTED d8:f1:5b:aa:bb:bb
wlan0: AP-STA-CONNECTED d8:f1:5b:aa:bb:bb
new client on port 443 from 10.42.42.40:8675
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:34662
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:20320
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.26:50709
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.26:50710
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.26:50711
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:21210
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.26:50713
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:8451
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:38290
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:33165
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:56976
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:10169
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:23876
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:8796
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:47355
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:20866
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:20342
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:18092
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:56317
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:53188
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:9058
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:16572
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:664
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:28315
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:5391
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:5943
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:6542
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:7658
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:32448
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:62994
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
^C1575998548: mosquitto version 1.4.14 terminating
new client on port 443 from 10.42.42.40:5723
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:27153
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
new client on port 443 from 10.42.42.40:41079
('could not establish sslpsk socket:', SSLError('No cipher can be selected.',))
^CTraceback (most recent call last):
  File "./psk-frontend.py", line 111, in <module>
    main()
  File "./psk-frontend.py", line 104, in main
    r,_,_ =  select.select(readables, [], [])
KeyboardInterrupt
^Cwlan0: AP-STA-DISCONNECTED d8:f1:5b:aa:bb:bb
wlan0: AP-STA-DISCONNECTED a4:08:ea:27:80:37
AP closed
Stopping DNSMASQ server...
```

I'm a Linux NOOB, so don't know what to make of any of the log info.

**Comment by rebel7580** [comment]
Sorry wrong place!!!
